spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://db.ctd.academy:3306/pi21023c02_GRUPO7
    username: pi21023c02_GRUPO7
    password: yi4Ohdu5
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: event
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
