spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/int2
    username: nacho
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: event
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
